"""
PDF Generation Service — Export recipes into clean, printable PDF documents.
"""
import io
from typing import Dict, Any

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False


def _generate_fallback_text(title: str, body: str) -> bytes:
    content = f"--- {title} ---\n\n{body}\n\nGenerated by Inverse Cooking AI"
    return content.encode('utf-8')


def generate_recipe_pdf(recipe_data: Dict[str, Any]) -> bytes:
    """Generate printable PDF byte stream for a structured recipe dictionary."""
    if not REPORTLAB_AVAILABLE:
        dish_name = recipe_data.get("dish_name", "Recipe")
        chef = recipe_data.get("chef", "N/A")
        restaurant = recipe_data.get("restaurant", "N/A")
        ingredients = "\n".join([f"- {i}" for i in recipe_data.get("ingredients", [])])
        steps = "\n".join([f"{idx}. {s}" for idx, s in enumerate(recipe_data.get("steps", []), 1)])
        body = f"Chef: {chef}\nRestaurant: {restaurant}\n\nINGREDIENTS:\n{ingredients}\n\nCOOKING STEPS:\n{steps}"
        return _generate_fallback_text(dish_name, body)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'RecipeTitle',
        parent=styles['Heading1'],
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#1E293B"),
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        'RecipeSubTitle',
        parent=styles['Normal'],
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#64748B"),
        spaceAfter=12
    )

    section_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontSize=15,
        leading=19,
        textColor=colors.HexColor("#E63946"),
        spaceBefore=10,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'RecipeBody',
        parent=styles['Normal'],
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#334155")
    )

    story = []

    # Title & Metadata
    dish_name = recipe_data.get("dish_name", "Recipe")
    chef = recipe_data.get("chef", "Chef Verified")
    restaurant = recipe_data.get("restaurant", "Inverse Cooking")
    cuisine = recipe_data.get("cuisine", "N/A")
    price = recipe_data.get("base_price", "N/A")

    story.append(Paragraph(dish_name, title_style))
    story.append(Paragraph(f"<b>Chef:</b> {chef} &nbsp;|&nbsp; <b>Restaurant:</b> {restaurant} &nbsp;|&nbsp; <b>Cuisine:</b> {cuisine} &nbsp;|&nbsp; <b>Price:</b> ₹{price}", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=12))

    # Description if present
    if recipe_data.get("description"):
        desc_style = ParagraphStyle('Desc', parent=body_style, fontStyle='Italic', textColor=colors.HexColor("#475569"))
        story.append(Paragraph(f"<i>{recipe_data['description']}</i>", desc_style))
        story.append(Spacer(1, 8))

    # Ingredients Section
    story.append(Paragraph("Verified Ingredients", section_style))
    ingredients = recipe_data.get("ingredients", [])
    if ingredients:
        for ing in ingredients:
            story.append(Paragraph(f"• {ing}", body_style))
            story.append(Spacer(1, 3))
    else:
        story.append(Paragraph("No ingredients listed.", body_style))

    story.append(Spacer(1, 8))

    # Cooking Steps Section
    story.append(Paragraph("Cooking Instructions", section_style))
    steps = recipe_data.get("steps", [])
    if steps:
        for idx, step in enumerate(steps, 1):
            story.append(Paragraph(f"<b>{idx}.</b> {step}", body_style))
            story.append(Spacer(1, 5))
    else:
        story.append(Paragraph("No cooking steps provided.", body_style))

    # Add-ons if present
    addons = recipe_data.get("premium_add_ons", [])
    if addons:
        story.append(Spacer(1, 8))
        story.append(Paragraph("Available Premium Add-ons", section_style))
        for addon in addons:
            story.append(Paragraph(f"• <b>{addon['name']}</b> (+₹{addon.get('price', 0)})", body_style))
            story.append(Spacer(1, 3))

    # Footer
    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0"), spaceAfter=8))
    footer_style = ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8.5, textColor=colors.HexColor("#94A3B8"), alignment=1)
    story.append(Paragraph("Generated by Inverse Cooking AI • Culinary Intelligence System", footer_style))

    doc.build(story)
    pdf_data = buffer.getvalue()
    buffer.close()
    return pdf_data


def generate_text_recipe_pdf(dish_name: str, recipe_markdown: str) -> bytes:
    """Generate printable PDF byte stream from markdown/plain text AI recipe output."""
    if not REPORTLAB_AVAILABLE:
        return _generate_fallback_text(dish_name, recipe_markdown)

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'RecipeTitleText',
        parent=styles['Heading1'],
        fontSize=24,
        leading=28,
        textColor=colors.HexColor("#1E293B"),
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'RecipeBodyText',
        parent=styles['Normal'],
        fontSize=10.5,
        leading=15,
        textColor=colors.HexColor("#334155")
    )

    story = [
        Paragraph(dish_name or "AI Generated Recipe", title_style),
        HRFlowable(width="100%", thickness=1, color=colors.HexColor("#CBD5E1"), spaceAfter=12)
    ]

    lines = recipe_markdown.splitlines()
    for line in lines:
        cleaned_line = line.strip()
        if not cleaned_line:
            story.append(Spacer(1, 6))
            continue
        if cleaned_line.startswith("#"):
            heading_text = cleaned_line.lstrip("#").strip()
            h_style = ParagraphStyle('H', parent=styles['Heading2'], fontSize=14, textColor=colors.HexColor("#E63946"), spaceBefore=8, spaceAfter=4)
            story.append(Paragraph(heading_text, h_style))
        else:
            safe_text = cleaned_line.replace("<", "&lt;").replace(">", "&gt;")
            story.append(Paragraph(safe_text, body_style))
            story.append(Spacer(1, 4))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E2E8F0"), spaceAfter=8))
    footer_style = ParagraphStyle('FooterText', parent=styles['Normal'], fontSize=8.5, textColor=colors.HexColor("#94A3B8"), alignment=1)
    story.append(Paragraph("Generated by Inverse Cooking AI • Culinary Intelligence System", footer_style))

    doc.build(story)
    pdf_data = buffer.getvalue()
    buffer.close()
    return pdf_data
